[env:esp32c3dev]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
	RobTillaart/AD9833
	adafruit/Adafruit NeoPixel
extra_scripts = post:extra_scripts/uploadfs.py
